### ISSUE TITLE
'wolkenkit start' hangs after 'started boards-node-module'

### ISSUE THREAD

**Issue by sscholle** [thenativeweb/wolkenkit-boards#7]
The Console looks like:

  Starting the application...
  Verifying health on environment default...
  Verifying application status...
  Verifying that ports are available...
  Setting up network...
  Building Docker images...
  Starting Docker containers...
⠦(node:36769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ExecutableFailed: docker: Error response from daemon: driver failed programming external connectivity on endpoint boards-depot-file (cd95a016e0b5fa1c4b7e753a223e40f824ff76f7c0dfedcfd74d575ebc67b719): Bind for 0.0.0.0:3001 failed: port is already allocated.

(node:36769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋(node:36769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ExecutableFailed: docker: Error response from daemon: driver failed programming external connectivity on endpoint boards-mongodb (b0da8b659ae660606b1333e5f10b27b346aaf9095c91b37772f7361c307517d1): Bind for 0.0.0.0:3002 failed: port is already allocated.

⠼(node:36769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ExecutableFailed: docker: Error response from daemon: driver failed programming external connectivity on endpoint boards-postgres (9f7e55cb6615d8ccd417cee30a22067f2dc4b7e3f64c8bdbcc078ba8eb88058d): Bind for 0.0.0.0:3003 failed: port is already allocated.

(node:36769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): ExecutableFailed: docker: Error response from daemon: driver failed programming external connectivity on endpoint boards-rabbitmq (66320fefe04b73287872ba9aaf5fd0f31dc6aaa432f0eaab716627a869407339): Bind for 0.0.0.0:3005 failed: port is already allocated.

  Started boards-node-modules (1/8).
⠦

**Comment by goloroden** [comment]
Hi @sscholle!

Thanks for bringing up this issue!

Which version of the wolkenkit CLI are you using?
(You can find it out by running `wolkenkit --version`)

**Comment by goloroden** [comment]
@sscholle Is this still relevant?

**Comment by goloroden** [comment]
Closed since it is apparently not relevant any more.
